
export const TESSERACT_LANGUAGES = [
    { code: 'afr', name: 'Afrikaans' },
    { code: 'amh', name: 'Amharic' },
    { code: 'ara', name: 'Arabic' },
    { code: 'asm', name: 'Assamese' },
    { code: 'aze', name: 'Azerbaijani' },
    { code: 'aze_cyrl', name: 'Azerbaijani (Cyrillic)' },
    { code: 'bel', name: 'Belarusian' },
    { code: 'ben', name: 'Bengali' },
    { code: 'bod', name: 'Tibetan' },
    { code: 'bos', name: 'Bosnian' },
    { code: 'bul', name: 'Bulgarian' },
    { code: 'cat', name: 'Catalan' },
    { code: 'ceb', name: 'Cebuano' },
    { code: 'ces', name: 'Czech' },
    { code: 'chi_sim', name: 'Chinese (Simplified)' },
    { code: 'chi_tra', name: 'Chinese (Traditional)' },
    { code: 'chr', name: 'Cherokee' },
    { code: 'cym', name: 'Welsh' },
    { code: 'dan', name: 'Danish' },
    { code: 'deu', name: 'German' },
    { code: 'dzo', name: 'Dzongkha' },
    { code: 'ell', name: 'Greek' },
    { code: 'eng', name: 'English' },
    { code: 'enm', name: 'English (Middle)' },
    { code: 'epo', name: 'Esperanto' },
    { code: 'est', name: 'Estonian' },
    { code: 'eus', name: 'Basque' },
    { code: 'fas', name: 'Persian' },
    { code: 'fin', name: 'Finnish' },
    { code: 'fra', name: 'French' },
    { code: 'frk', name: 'Frankish' },
    { code: 'frm', name: 'French (Middle)' },
    { code: 'gle', name: 'Irish' },
    { code: 'glg', name: 'Galician' },
    { code: 'grc', name: 'Greek (Ancient)' },
    { code: 'guj', name: 'Gujarati' },
    { code: 'hat', name: 'Haitian' },
    { code: 'heb', name: 'Hebrew' },
    { code: 'hin', name: 'Hindi' },
    { code: 'hrv', name: 'Croatian' },
    { code: 'hun', name: 'Hungarian' },
    { code: 'iku', name: 'Inuktitut' },
    { code: 'ind', name: 'Indonesian' },
    { code: 'isl', name: 'Icelandic' },
    { code: 'ita', name: 'Italian' },
    { code: 'ita_old', name: 'Italian (Old)' },
    { code: 'jav', name: 'Javanese' },
    { code: 'jpn', name: 'Japanese' },
    { code: 'kan', name: 'Kannada' },
    { code: 'kat', name: 'Georgian' },
    { code: 'kat_old', name: 'Georgian (Old)' },
    { code: 'kaz', name: 'Kazakh' },
    { code: 'khm', name: 'Khmer' },
    { code: 'kir', name: 'Kirghiz' },
    { code: 'kor', name: 'Korean' },
    { code: 'kur', name: 'Kurdish' },
    { code: 'lao', name: 'Lao' },
    { code: 'lat', name: 'Latin' },
    { code: 'lav', name: 'Latvian' },
    { code: 'lit', name: 'Lithuanian' },
    { code: 'mal', name: 'Malayalam' },
    { code: 'mar', name: 'Marathi' },
    { code: 'mkd', name: 'Macedonian' },
    { code: 'mlt', name: 'Maltese' },
    { code: 'msa', name: 'Malay' },
    { code: 'mya', name: 'Burmese' },
    { code: 'nep', name: 'Nepali' },
    { code: 'nld', name: 'Dutch' },
    { code: 'nor', name: 'Norwegian' },
    { code: 'ori', name: 'Oriya' },
    { code: 'pan', name: 'Punjabi' },
    { code: 'pol', name: 'Polish' },
    { code: 'por', name: 'Portuguese' },
    { code: 'pus', name: 'Pashto' },
    { code: 'ron', name: 'Romanian' },
    { code: 'rus', name: 'Russian' },
    { code: 'san', name: 'Sanskrit' },
    { code: 'sin', name: 'Sinhala' },
    { code: 'slk', name: 'Slovak' },
    { code: 'slv', name: 'Slovenian' },
    { code: 'spa', name: 'Spanish' },
    { code: 'spa_old', name: 'Spanish (Old)' },
    { code: 'sqi', name: 'Albanian' },
    { code: 'srp', name: 'Serbian' },
    { code: 'srp_latn', name: 'Serbian (Latin)' },
    { code: 'swan', name: 'Swahili' },
    { code: 'swe', name: 'Swedish' },
    { code: 'syr', name: 'Syriac' },
    { code: 'tam', name: 'Tamil' },
    { code: 'tel', name: 'Telugu' },
    { code: 'tgk', name: 'Tajik' },
    { code: 'tgl', name: 'Tagalog' },
    { code: 'tha', name: 'Thai' },
    { code: 'tir', name: 'Tigrinya' },
    { code: 'tur', name: 'Turkish' },
    { code: 'uig', name: 'Uighur' },
    { code: 'ukr', name: 'Ukrainian' },
    { code: 'urd', name: 'Urdu' },
    { code: 'uzb', name: 'Uzbek' },
    { code: 'uzb_cyrl', name: 'Uzbek (Cyrillic)' },
    { code: 'vie', name: 'Vietnamese' },
    { code: 'yid', name: 'Yiddish' }
];
